### PR TITLE
Updated 3 employer contributions pages

### PR DESCRIPTION
**Pull request by MaryCong**
- What was the total contribution made by employer x
- Were employer contributions made by other employers 
- Check your answers and change details (employer contributions)

### CODE REVIEW

**Review by joshhumphreys — COMMENTED** [review]
One outstanding question RE row 2028 - looks as though it's been deleted and replaced with the same thing, will wait for confirmation from @MaryCong before I approve.

**Comment by kberec** [comment]
> One outstanding question RE row 2028 - looks as though it's been deleted and replaced with the same thing, will wait for confirmation from @MaryCong before I approve.

I think that's just the new line character removed.

**Comment by MaryCong** [comment]
Yeah, I don't remember touching that line, so not sure what happened there. @kberec, if it's not going to mess up the code, is it ok to be approved?

**Comment by kberec** [comment]
> Yeah, I don't remember touching that line, so not sure what happened there. @kberec, if it's not going to mess up the code, is it ok to be approved?

There are some conflicts we need to resolve first. We can do it on Monday.

**Comment by MaryCong** [comment]
Sure, no rush, thanks!

**Review by kberec — APPROVED** [review]

**Pull request merged**
